### PR TITLE
implemented language path prefixing and associated workarounds

### PR DESCRIPTION
**Pull request by liboan**
This was not as easy as we thought- had to do two workarounds.

1. Language-switching on the toolbar had to be done by manually slicing the current path's language prefix out and appending the other language code, because language prefix appending only works for reverse url resolution and not `{{ request.path }}`.

2. Language prefixing only works in a root URLconf (`cafe/urls.py`) meaning that the urls in `pcari/urls.py` are all blanket translated. This breaks the service worker- requesting `/pcari/sw.js` causes a redirect for language prefixing, and service worker code is not run for security reasons. Requesting one of the languages, such as `/en/pcari/sw.js` will make it unable to cache resources underneath `/tl/` and vice-versa. 
My workaround was similar to how Justin got the admin panel to work- I placed a url for `sw.js` in both `cafe/urls.py` and `pcari/urls.py` so that I could request `/sw.js`, which was not redirected by language prefixing.

### CODE REVIEW

**Comment by liboan** [comment]
Jonathan's sanity tests in `tests.py` are getting blown up because language prefixing causes redirects, hence the 302s. I'm more worried about the failed test `test_empty_save` where an empty `Respondent` was successfully pushed to the database. Not sure why any of the above changes would have caused this to break because that is a test of model behavior only, not views or urls

**Comment by jonathan-j-lee** [comment]
To pass the build, you need to correct the `push` method of the save test case--use `reverse('pcari:save-response')`.

**Comment by liboan** [comment]
Implemented suggested changes, I think it's good to go now

**Comment by jonathan-j-lee** [comment]
The changes here are a subset of #68, so this PR is now unnecessary.

**Pull request closed without merging**
